name: Run Python

on:
  push:

jobs:
  run-python:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python
        run: python main.py