name: Run Python

on:
  push:

jobs:
  run-python:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python
        run: C:\Users\snike\AppData\Local\Programs\Python\Python313\python.exe main.py